---
  - name: Copy Dockerfile to remote host
    copy:
      src: 'Dockerfile'
      dest: './Dockerfile'
      owner: ubuntu
      group: ubuntu
      mode: 0644

  - name: Build a image from Ubuntu installing RabbitMQ
    docker_image:
      path: .
      name: "{{ image_name }}"
      tag: "{{ image_tag }}"

  - name: Create and start node 3
    docker_container:
      name: "{{ container_name }}"
      hostname: "{{ hostnames.hn_3 }}"
      image: "{{ image_name }}:{{ image_tag }}"
      state: started
      ports:
        - "4369:4369"
        - "5672:5672"
        - "25672:25672"
        - "35672:25672"
      env:
        RABBITMQ_NODENAME: "{{ nodenames.node3 }}"
      etc_hosts: >
        {
          "{{ hostnames.hn_2 }}": "{{ ip_nodes.ip2 }}",
          "{{ hostnames.hn_1 }}": "{{ ip_nodes.ip1 }}"
        }

  - name: Add my own Erlang Cookie to node 3
    command: docker exec "{{ container_name }}" /bin/bash -c "echo "'{{ erlang_cookie }}'" > /var/lib/rabbitmq/.erlang.cookie"
  
  - name: Restart container
    docker_container:
      name: "{{ container_name }}"
      state: started
      restart: yes

  - name: Stop RabbitMQ app
    command: docker exec "{{ container_name }}" /bin/bash -c "rabbitmqctl stop_app"

  - name: Join to cluster of node 1
    command: docker exec "{{ container_name }}" /bin/bash -c "rabbitmqctl join_cluster "'{{ nodenames.node1 }}'"@"'{{ hostnames.hn_1 }}'

  - name: Start RabbitMQ app
    command: docker exec "{{ container_name }}" /bin/bash -c "rabbitmqctl start_app"